FROM python:3.13-slim-trixie AS builder

COPY --from=ghcr.io/astral-sh/uv:0.11.3 /uv /uvx /bin/

WORKDIR /app
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_PREFERENCE=only-managed \
    UV_PYTHON=3.14

# Symlink the builder path to match distroless' runtime path (/usr/bin/python)
RUN ln -s /usr/local/bin/python /usr/bin/python

COPY uv.lock pyproject.toml ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-install-project --no-dev
COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

RUN chmod -R a+rx /app/.venv

FROM gcr.io/distroless/python3-debian13

WORKDIR /app

# Copy the entire app directory (which includes your .venv and packages)
COPY --from=builder --chown=1000:1000 /app .

# Inject the virtualenv's site-packages into the Python runtime search path
ENV PYTHONPATH="/app/.venv/lib/python3.13/site-packages"

USER 1000:1000

# Invoke the module using the native distroless python interpreter
ENTRYPOINT ["/app/.venv/bin/python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

